### ISSUE TITLE
The version of the transformer package

### ISSUE THREAD

**Issue by LUOyk1999** [gecgomes/ICD_Coding_MSAM#1]
Hi, your work is excellent! I would like to ask where I can find your `requirements.txt` file because I can't seem to locate it. I want to know the version of the transformer package. Thank you!

```
Load MIMIC-III-top50 dataset
Load text...
Load 1hot labels...
Load Tokenizer...
Load Model...
Some weights of MegatronBertForSequenceClassification were not initialized from the model checkpoint at UFNLP/gatortron-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/data2/yuankai/miniconda3/lib/python3.12/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
======= LETS TRAIN ======
... Starting to Evaluate model (val set) ...
Traceback (most recent call last):
  File "/home/data2/yuankai/miniconda3/lib/python3.12/site-packages/transformers/tokenization_utils_base.py", line 762, in convert_to_tensors
    tensor = as_tensor(value)
             ^^^^^^^^^^^^^^^^
  File "/home/data2/yuankai/miniconda3/lib/python3.12/site-packages/transformers/tokenization_utils_base.py", line 724, in as_tensor
    return torch.tensor(value)
           ^^^^^^^^^^^^^^^^^^^
TypeError: not a sequence

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/data2/yuankai/ICD_Coding_MSAM/Scripts/main.py", line 230, in <module>
    main()
  File "/home/data2/yuankai/ICD_Coding_MSAM/Scripts/main.py", line 185, in main
    trainer.evaluate(eval_dataset = val_dataset)
  File "/home/data2/yuankai/miniconda3/lib/python3.12/site-packages/transformers/trainer.py", line 3641, in evaluate
    output = eval_loop(
             ^^^^^^^^^^
  File "/home/data2/yuankai/miniconda3/lib/python3.12/site-packages/transformers/trainer.py", line 3816, in evaluation_loop
    for step, inputs in enumerate(dataloader):
  File "/home/data2/yuankai/miniconda3/lib/python3.12/site-packages/accelerate/data_loader.py", line 454, in __iter__
    current_batch = next(dataloader_iter)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/data2/yuankai/miniconda3/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/data2/yuankai/miniconda3/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data2/yuankai/miniconda3/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/data2/yuankai/miniconda3/lib/python3.12/site-packages/transformers/trainer_utils.py", line 812, in __call__
    return self.data_collator(features)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data2/yuankai/miniconda3/lib/python3.12/site-packages/transformers/data/data_collator.py", line 271, in __call__
    batch = pad_without_fast_tokenizer_warning(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data2/yuankai/miniconda3/lib/python3.12/site-packages/transformers/data/data_collator.py", line 66, in pad_without_fast_tokenizer_warning
    padded = tokenizer.pad(*pad_args, **pad_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data2/yuankai/miniconda3/lib/python3.12/site-packages/transformers/tokenization_utils_base.py", line 3450, in pad
    return BatchEncoding(batch_outputs, tensor_type=return_tensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data2/yuankai/miniconda3/lib/python3.12/site-packages/transformers/tokenization_utils_base.py", line 227, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "/home/data2/yuankai/miniconda3/lib/python3.12/site-packages/transformers/tokenization_utils_base.py", line 778, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`input_ids` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
```

My version:
```
Python 3.12.2
transformers             4.42.4
tensorflow               2.16.2
tf_keras                 2.16.0
```

**Comment by gecgomes** [comment]
Hello :D !!! Thank you for contacting us and thank you very much for your interest in our work. Sorry I completely forgot to add the requirements file, I've already uploaded it, you can find it now in the repository! I've also made some minor deprecation fixes to the original code, so consider pulling it again and update your fork! If you have any more problems getting the code working, don't hesitate to contact us again! I'll help you all I can! Have a nice day :)

**Comment by jaanaltosaar** [comment]
Thank you so much from our team @onefact :) excited to replicate!

**Comment by jaanaltosaar** [comment]
Thank you so much from our team @onefact :) excited to replicate!

**Comment by LUOyk1999** [comment]
Thank you very much! I have successfully run the code!
